{% set name = "extranormal3" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/extranormal3-{{ version }}.tar.gz
  sha256: 3a37612c1be26043f9790ebc45f1e5cc75e4ecb8864b1bb679cdd547b09cdbff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - extranormal3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/extranormal3/
  summary: Quick normalization of a bunch of Quick-EXAFS spectra
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
